### ISSUE TITLE
mwlwifi crash/won't init on wrt3200acm on latest builds.

### ISSUE THREAD

**Issue by j03ll0b0** [divestedcg/Divested-WRT#2]
Hello,

last working build:

Divested-WRT SNAPSHOT r26883+10-75cd4ef48d / LuCI Master 24.188.41532~d3bf675

building using the instructions from the divestedwrt website. tried completely erasing the openwrt folder to start over again, same behavior.

kernel and system logs along the faulty sysupdate binary:
[Archive.zip](https://github.com/user-attachments/files/16302107/Archive.zip)

**Comment by SkewedZeppelin** [comment]
did you revert the commits using the command noted in the changelog?

**Comment by j03ll0b0** [comment]
> did you revert the commits using the command noted in the changelog?

this?  git revert 419ceead 192afd31 7ca4190c 1bfcc1ea

nope, did know ... if I get started with removing the whole openwrt folder and do the "How to create my own builds?" as I used to, do I still need to do the revert the commits? I'll give it a try anyways...

**Comment by SkewedZeppelin** [comment]
the revert is necessary regardless until the regression is fixed

**Comment by j03ll0b0** [comment]
built Divested-WRT SNAPSHOT r26972+14-2bebf13357 / LuCI Master 24.201.48886~b3ea37c after doing the  git revert 419ceead 192afd31 7ca4190c 1bfcc1ea and now everything is working just fine, thanks. I confirm this is the temporary solution until the regression is fixed.
