### ISSUE TITLE
Error creating peers on Wireguard on 20240717-00

### ISSUE THREAD

**Issue by PickMeNow** [divestedcg/Divested-WRT#3]
Hi there,

Running the last version:  20240717-00
Router: wrt32x
When trying to set up a wireguard vpn, once I click add peer i get an error saying:

TypeError
Cannot read properties of null (reading 'firstChild')

Doesn't allow me to add peers or edit their configuration if I manually import a configuration file

**Comment by SkewedZeppelin** [comment]
I can't reproduce this issue
maybe try another browser?

also no changes are made to luci like this, so an issue like this is better reported upstream, if you encounter it in another browser too

**Comment by PickMeNow** [comment]
Tested in a new browser didn't fix the issue,
I was able to fix it somehow by updating luci-base and luci-mod-network

Now it works  :+1:
